### ISSUE TITLE
Will this project be open source? 

### ISSUE THREAD

**Issue by Wang-jun-yu** [BICLab/EMS-YOLO#1]
Will this project be open source? Thanks

**Comment by Wang-jun-yu** [comment]
At present, there is only one readme.md file in the code. Will the specific code of the project be open sourced in the future?

**Comment by BICLab** [comment]
coming soon

**Comment by BICLab** [comment]
> At present, there is only one readme.md file in the code. Will the specific code of the project be open sourced in the future?

coming soon

**Comment by Wang-jun-yu** [comment]
Thank you for your reply. Really looking forward to the release of this project. Hope it's coming soon!

**Comment by Scarecrow1010** [comment]
Looking forward to your open source code very much!

**Comment by AiladReb** [comment]
Could you tell me when are you willing to share your code? I'm really looking forward to this project.

**Comment by yeyun122** [comment]
Look forward to the author's work.

**Comment by TomTHChen** [comment]
Looking forward to your code too :)

**Comment by BICLab** [comment]
The code is now open source.
