### ISSUE TITLE
This repo lacks a lot of important things

### ISSUE THREAD

**Issue by Goer17** [BICLab/EMS-YOLO#10]
I've noticed that several blocks seem to be missing from the repository, and I'm having difficulty locating the EMS-ResNet structure referenced in your paper. Could you possibly guide me on where to find it or provide any additional information? Thank you for your assistance.

**Comment by Goer17** [comment]
I finished

**Comment by one00101** [comment]
> I finished

have you succeed in GEN1 dataset?
