### ISSUE TITLE
Gen1 dataset

### ISSUE THREAD

**Issue by Chrazqee** [BICLab/EMS-YOLO#2]
Hi, @Qiaoyi-Su I'd like to know, how should I use the `Gen1` dataset and have you preprocessed the `Gen1` dataset? It seems that this `repo` does not provide fully training support. Looking forward to a reply！

**Comment by sjoks93** [comment]
It would be nice to provide at least some information about the preprocessing used for the dataset.

**Comment by SamanthaZhang-stu** [comment]
I noticed you had a question about the Gen1 dataset, and I share the same inquiry. Have you received any updates on how to use the dataset or if it has been preprocessed? Any information would be greatly appreciated!
